### ISSUE TITLE
Zet de development stack op in de App repository

### ISSUE THREAD

**Issue by Hion-V** [KoeleKikkersKlub/PexFroge-App#1]

**Comment by Hion-V** [comment]
finished in c24f5a3c0a34894029a29feb1f26a1cb9c04e56e

**Comment by Hion-V** [comment]
Fixed missing .env while reviewing with @m4rkieeee. Fixed in commit f8aeccb8b11658fe50f809f5c1cdda5448104eb0

**Comment by m4rkieeee** [comment]
Fixes confirmed to have fixed the issue, WSL recommended to run project else go fioys. ( for windows users )
