### ISSUE TITLE
Update de readme

### ISSUE THREAD

**Issue by Hion-V** [KoeleKikkersKlub/PexFroge-App#2]
update de readme om het setup proces voor de dev omgeving te documenteren, reflectievelijk van de changes die zijn afgehandeld voor #1

**Comment by Hion-V** [comment]
Issue is ready for review. Please confirm the changes @m4rkieeee

**Comment by m4rkieeee** [comment]
Icecream so good yes yes yes. It works for WSL/Linux based machines :)

**Comment by Hion-V** [comment]
> Icecream so good yes yes yes. It works for WSL/Linux based machines :)

Halal. Marking this issue as completed then.
